Description:                       "Hygieia Quickstart - Database Stack"

Parameters:
  DBInstanceClass:
    Description:                   "The database instance type"
    Type:                          "String"
    AllowedValues:
      - "db.r4.large"
      - "db.r4.xlarge"
      - "db.r4.2xlarge"
      - "db.r4.4xlarge"
      - "db.r4.8xlarge"
      - "db.r4.16xlarge"

  ServiceName:
    Description :                  "Cluster name"
    Type:                          "String"
    MinLength:                     "1"
    MaxLength:                     "64"
    AllowedPattern :               "[a-zA-Z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*"
    ConstraintDescription :        "Must begin with a letter and contain only alphanumeric characters."

  MasterUser:
    NoEcho:                        "true"
    Description :                  "The database admin account username"
    Type:                          "String"
    MinLength:                     "1"
    MaxLength:                     "16"
    AllowedPattern:                "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription :        "Must begin with a letter and contain only alphanumeric characters."

  MasterPassword:
    NoEcho:                        "true"
    Description :                  "The database admin account password"
    Type:                          "String"
    MinLength:                     "1"
    MaxLength:                     "41"
    AllowedPattern :               "[a-zA-Z0-9]+"
    ConstraintDescription :        "must contain only alphanumeric characters."

  SubnetIds:
    Description:                   "List of subnets to create DBSubnetGroup from"
    Type:                          "String"

  VpcSecurityGroupIds:
    Description:                   "List of security group IDs to use with the DocumentDB"
    Type:                          "String"

Resources:
  DBClusterParameterGroup:
    Type:                          "AWS::DocDB::DBClusterParameterGroup"
    Properties:
      Description:                 "Parameter group with TLS disabled"
      Family:                      "docdb3.6"
      Parameters:
        tls:                       "disabled"
      Tags:
        -
          Key:                     "Name"
          Value:                   "docdb3.6-no-tls"

  DBSubnetGroup:
    Type:                          "AWS::DocDB::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription:    "Hygieia DocumentDB subnet group"
      DBSubnetGroupName:           !Sub "${ServiceName}-DBSubnetGroup"
      SubnetIds:                   !Split [",", !Ref SubnetIds]

  DBCluster:
    Type:                          "AWS::DocDB::DBCluster"
    DeletionPolicy:                Delete
    Properties:
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      DBClusterIdentifier:         !Ref ServiceName
      DBSubnetGroupName:           !Ref DBSubnetGroup
      MasterUsername:              !Ref MasterUser
      MasterUserPassword:          !Ref MasterPassword
      VpcSecurityGroupIds:         [!Ref VpcSecurityGroupIds]
    DependsOn:
      - DBSubnetGroup
      - DBClusterParameterGroup

  DBInstance:
    Type:                          "AWS::DocDB::DBInstance"
    Properties:
      DBClusterIdentifier:         !Ref DBCluster
      DBInstanceIdentifier:        !Join ["-", [!Ref ServiceName, "InstanceName"] ]
      DBInstanceClass:             !Ref DBInstanceClass
    DependsOn:
      - DBCluster

Outputs:
  ClusterId:
    Value:                         !Ref DBCluster
  ClusterEndpoint:
    Value:                         !GetAtt DBCluster.Endpoint
  ClusterReadEndpoint:
    Value:                         !GetAtt DBCluster.ReadEndpoint
  ClusterPort:
    Value:                         !GetAtt DBCluster.Port
  InstanceId:
    Value:                         !Ref DBInstance
  InstancePort:
    Value:                         !GetAtt DBInstance.Port
  InstanceEndpoint:
    Value:                         !GetAtt DBInstance.Endpoint
