#!/usr/bin/env sh

aws cloudformation deploy --s3-bucket hygieia-quickstart --region us-east-1 --template-file deploy.yml --stack-name Hygieia-Quickstart --capabilities CAPABILITY_NAMED_IAM --parameter-overrides $(jq -r '.[] | [.ParameterKey, .ParameterValue] | join("=")' params.json)
